### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by PPastene**
This pull request includes a Dockerfile, docker-compose.yml, and a basic configuration for NGINX. The Dockerfile uses both alpine and FPM image for PHP version 7.4 and includes npm, composer, bash, and all the packages needed for Laravel. The docker-compose.yml includes the image building, the persistence for both images and database, and MySQL and NGINX images

In this pull request, the following are missing:

- [ ] SSL config
- [ ] VirtualHost config

To make it work run the following command

`docker-compose up -d --build` (the --build flag will build the dockerfile every time while the -d will run the images on background)

To enter the container to run composer, npm, and artisan

`docker exec -it bdgt_php bash`

When you use the .env for the database you need to change the DB_HOST with the container's name of the database, in this case, bdgt_mysql. Remember to check it out before running `php artisan migrate`

To stop the containers

`docker-compose down` (you can use the -v flag to also delete the containers and volumes)

Feel free to edit it as you will, I'm still learning Docker but at least is something to replace Vagrant

### CODE REVIEW

**Comment by PPastene** [comment]
Hey, I've noticed that my pull request was rejected by a fail assertion on PHPUnit, but now I've run it on my local environment and all the tests were successful without making any change. I'll try to commit the pull request again

**Comment by sbine** [comment]
@PPastene that was an intermittent test failure (occasionally SQLite saves `updated_at` values 1 second later than what Laravel thinks they should be). I re-ran the suite and it looks good, and I'll give this a proper review when I can test it out. Thanks!

**Comment by sbine** [comment]
This is working great locally, so I'm going to merge it and we can keep iterating on it in future PRs. Thank you!

**Comment by Saibamen** [comment]
What are the sizes for images?

**Comment by sbine** [comment]
@Saibamen 451MB for the image we're building, according to `docker image ls`.

image

**Pull request merged**
