### PR TITLE
Select nice-looking static colors for reports

### PR DESCRIPTION
**Pull request by ActuallyConnor**
#29  Select nice-looking static colors for reports
- Selecting a new set of colors that look nice together but are easy to differentiate
- Updating both reports so categories generally keep appearing in the same color through page refreshes (but it's OK if they change when the list of categories changes)

This is the same colour palette used by the bank RBC (Royal Bank of Canada) on their own personal budget tool. Right now the colours are attached to each category based on order. If you would prefer the colours in a different order please let me know.

This is an image of RBC's myFinance budget tracking tool so you can see their colour palette.
rbc

This is the colour palette implemented on the Per Category Report
bdgt-category

This is the colour palette implemented on the Over Time Report
bdgt-over-time

### CODE REVIEW

**Comment by sbine** [comment]
@ActuallyConnor I really like this color set but there are some conflicts with #40 which moved the colors to a shared location so they can be updated in one place.

I'm going to mark your PR as accepted, please fix the conflicts if you're able to, but if not I will get to it. Thanks for your contribution!

**Comment by ActuallyConnor** [comment]
Hey @sbine I've fixed the merge conflicts and update my PR 😄

**Comment by sbine** [comment]
@ActuallyConnor so sorry, I merged some more PRs before this one and triggered conflicts on the frontend assets again. If you check the box in the PR "Allow edits from maintainers" I'll fix them for you.

I'll need to sort out proper frontend builds, this was less of an issue when it was just me 😄

**Comment by sbine** [comment]
Okay, #49 is merged which deletes those conflicting files in `public/`, so all you should need to do is merge the latest changes into your branch. Sorry for the hassle!

**Comment by sbine** [comment]
Figured out committing to your branch thanks to my coworker Jake's [awesome blog post](https://tighten.co/blog/adding-commits-to-a-pull-request/), my git remote syntax was a bit off. Thanks again!

**Pull request merged**
