### PR TITLE
Adding two icons to get better UI interface experience. First one, is in 'login' navbar button, and second in logout button.

### PR DESCRIPTION
**Pull request by diogolimas**
**Some screenshots about modification:**

1 - in login button:  
image

2 - In logout button: 
image

### CODE REVIEW

**Comment by diogolimas** [comment]
Can you insert Hacktoberfest label?

**Comment by diogolimas** [comment]
Can you insert the Hacktoberfest label?

**Comment by Saibamen** [comment]
Why SVG?

IMHO Font Awesome will be better

**Comment by sbine** [comment]
bdgt already pulls in Font Awesome, [here's an example](https://github.com/sbine/bdgt/blob/master/resources/views/dashboard.blade.php#L21) using the local dependency.

I'm on the fence about adding more icons to the UI (I feel it can be easy to go overboard with icon sets, and bdgt already uses a lot), but I'll pull this down locally when I have a bit more time and give it some thought.

**Comment by diogolimas** [comment]
In fact, icons improve the website experience. Don't worry, is better than use just text to make information available in buttons and links. 
If you want, I can change SVG icons to Font Awesome. What you think about this idea?

**Comment by diogolimas** [comment]
Or, if you feel good with this icons, could accept my modification and I progress in news modification using Font Awesome. What you think?

**Comment by sbine** [comment]
After considering this I'm not looking to add any more icons to bdgt's UI at this time. Thanks anyway!

**Pull request closed without merging**
